### ISSUE TITLE
I can't find the module in Magento Marketplace

### ISSUE THREAD

**Issue by bskimball** [hps/heartland-magento-extension#115]
Maybe provide a link in the readme.md for the module in the marketplace?

**Comment by slogsdon** [comment]
@bskimball Apologies for the inconvenience! We're currently working to get our extension approved and added to Magento Marketplace, but once that's complete, we'll be sure to get a link added to the README.

In the meantime, our current `master` branch is the latest code that was available on Magento Connect (version 1.4.8) before it was turned off.

Please let us know if there are any questions/concerns.

**Comment by bskimball** [comment]
Thanks
