### ISSUE TITLE
Credit Memo throws : Invalid Transaction ID. 

### ISSUE THREAD

**Issue by Jonathonbyrd** [hps/heartland-magento-extension#85]
We can process offline credit memos no problem, but trying to process a refund through Magento throws an Invalid Transaction ID. 

We only have this extension installed and no other payment sources available for customers.

     2016-06-16T18:02:17+00:00 ERR (3): 
     exception 'HpsArgumentException' with message 'Invalid Transaction Id' in /var/www/html/lib/SecureSubmit/src/Services/Gateway/HpsCreditService.php:218
     Stack trace:
     #0 /var/www/html/app/code/community/Hps/Securesubmit/Model/Payment.php(317): HpsCreditService->get(NULL)
     #1 /var/www/html/app/code/community/Hps/Securesubmit/Model/Payment.php(287): Hps_Securesubmit_Model_Payment->transactionActiveOnGateway(Object(Mage_Sales_Model_Order_Payment))
     #2 /var/www/html/app/code/core/Mage/Sales/Model/Order/Payment.php(693): Hps_Securesubmit_Model_Payment->refund(Object(Mage_Sales_Model_Order_Payment), '3.95')
     #3 /var/www/html/app/code/core/Mage/Sales/Model/Order/Creditmemo.php(458): Mage_Sales_Model_Order_Payment->refund(Object(Mage_Sales_Model_Order_Creditmemo))
     #4 /var/www/html/app/code/core/Mage/Sales/Model/Order/Creditmemo.php(540): Mage_Sales_Model_Order_Creditmemo->refund()
     #5 /var/www/html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/CreditmemoController.php(305): Mage_Sales_Model_Order_Creditmemo->register()
     #6 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_Order_CreditmemoController->saveAction()
     #7 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
     #8 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
     #9 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
     #10 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
     #11 /var/www/html/index.php(83): Mage::run('', 'store')
     #12 {main}

**Comment by slogsdon** [comment]
Hi @Jonathonbyrd! Was the extension installed from Magento Connect, or were the files obtained through GitHub/our developer portal? This looks to be similar to another issue we've seen recently that should have been corrected already.

**Comment by Jonathonbyrd** [comment]
The extension was installed from github about a month ago. I'll install your latest version and see if that fixes it.

**Comment by Jonathonbyrd** [comment]
Seems that your latest ver did fix this error.

**Comment by slogsdon** [comment]
@Jonathonbyrd Great to hear! Please let us know if you run into any issues moving forward.
