### ISSUE TITLE
HPS via Paypal not working

### ISSUE THREAD

**Issue by Jonathonbyrd** [hps/heartland-magento-extension#86]
There's a new feature in this extension that let's your customers offer paypal as a gateway to their existing MID. When our customer clicks "Checkout with PayPal" it tries to open a new window (as I think it should) but the window never loads.

Here are the credentials for our staging site. We have it locked with apache to prevent google from indexing it.

property | value
----- | -----
staging | http://ec2-52-34-95-94.us-west-2.compute.amazonaws.com/
apache username | staging
apache password | staging

**Comment by slogsdon** [comment]
Hi @Jonathonbyrd! On my end, i am presented with the production PayPal interface in the modal when continuing with payment on the checkout page. (I can provide a screenshot if you'd like). Would you be able to describe the issue you're experiencing? How do you currently have this enabled within your Magento admin?

If you'd like to continue this discussion via email, you can connect with me and the rest of my team at EntApp_DevPortal@e-hps.com.

**Comment by Jonathonbyrd** [comment]
Here's what we get when we test. Just a spinning icon from paypal that never ends.

![paypal-screen](https://cloud.githubusercontent.com/assets/18008666/16237728/b8e9e444-37ab-11e6-88a8-3cadc3c1a236.jpg)

**Comment by slogsdon** [comment]
I'm seeing this on my end.

![screen shot 2016-06-22 at 12 53 41 pm](https://cloud.githubusercontent.com/assets/647624/16275545/76ed87b2-3878-11e6-9f4b-c6e2fc4599f7.png)

Are there any messages in your PHP/webserver or Magento logs that could shed some light on this? How do you currently have PayPal configured under the HPS PayPal options?

**Comment by Jonathonbyrd** [comment]
I think it's intermittent. I get the login page about 3/5 times. I'll check the error logs

**Comment by Jonathonbyrd** [comment]
Seems that your latest module ext may have fixed this error.

**Comment by slogsdon** [comment]
@Jonathonbyrd Great to hear! Please let us know if you run into any issues moving forward.

**Comment by Jonathonbyrd** [comment]
I may have spoken too soon. Seems to be working in all browsers except Chrome.

**Comment by slogsdon** [comment]
Is this on Windows are MacOS? Are there any messages in your Magento or web server/PHP logs that may show if there is an exception being thrown that isn't be caught properly?

Chrome is my default browser on MacOS, and I have yet to come across this issue. Any help you can provide in narrowing down this issue will help me correct the cause

**Comment by Jonathonbyrd** [comment]
The client is no longer with me, so I can't provide any more information on the issue.
